E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Areas/Company/Models/Routes/AllRoutes.cs
namespace ETicketSystem.Web.Areas.Company.Models.Routes
{
	using Common.Constants;
	using Microsoft.AspNetCore.Mvc.Rendering;
	using Services.Company.Models;
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
	using Web.Models.Pagination;

	public class AllRoutes
    {
		public IEnumerable<CompanyRouteListingServiceModel> Routes { get; set; }

		public PaginationViewModel Pagination { get; set; }

		[Display(Name = WebConstants.FieldDisplay.StartDestination)]
		public int StartTown { get; set; }

		[Display(Name = WebConstants.FieldDisplay.EndDestination)]
		public int EndTown { get; set; }

		[DataType(DataType.Date)]
		[DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)]
		public DateTime? Date { get; set; }

		public IEnumerable<SelectListItem> Towns { get; set; }
	}
}

E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Areas/Company/Models/Routes/RouteFormModel.cs
namespace ETicketSystem.Web.Areas.Company.Models.Routes
{
	using Common.Constants;
	using Data.Enums;
	using Microsoft.AspNetCore.Mvc.Rendering;
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public class RouteFormModel : IValidatableObject
    {
		[Display(Name = WebConstants.FieldDisplay.RouteStartStation)]
		public int StartStation { get; set; }

		[Display(Name = WebConstants.FieldDisplay.RouteEndStation)]
		public int EndStation { get; set; }

		[DataType(DataType.Time)]
		[Display(Name = WebConstants.FieldDisplay.RouteDepartureTime)]
		[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = DataConstants.Route.DepartureTimeFormat)]
		public DateTime DepartureTime { get; set; }

		[DataType(DataType.Time)]
		public TimeSpan Duration { get; set; }

		[Required]
		[Display(Name = WebConstants.FieldDisplay.RouteBusType)]
		public BusType BusType { get; set; }

		[Range(DataConstants.Route.PriceMinValue, double.MaxValue,ErrorMessage = WebConstants.Message.PositivePrice)]
		public decimal Price { get; set; }

		public bool IsEdit { get; set; }

		public List<SelectListItem> TownsStations { get; set; }

		public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
		{
			if (this.Duration == new TimeSpan(0,0,0))
			{
				yield return new ValidationResult(WebConstants.Message.RouteDurationZeroLength);
			}
		}
	}
}

E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Models/Routes/BookTicketFormModel.cs
namespace ETicketSystem.Web.Models.Routes
{
	using Infrastructure.Attributes.Validation;
	using System;
	using System.Collections.Generic;

	public class BookTicketFormModel
    {
		public int RouteId { get; set; }

		public string CompanyId { get; set; }

		public string CompanyName { get; set; }

		public DateTime DepartureDateTime { get; set; }

		public TimeSpan Duration { get; set; }

		public int BusSeats { get; set; }

		public string StartStation { get; set; }

		public string EndStation { get; set; }

		public int StartTownId { get; set; }

		public int EndTownId { get; set; }

		[AtLeastOneRequired]
		public List<BusSeat> Seats { get; set; } = new List<BusSeat>();
    }
}

E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Models/Routes/BusSeat.cs
namespace ETicketSystem.Web.Models.Routes
{
	public class BusSeat
    {
		public int Value { get; set; }

		public string Text { get; set; }

		public bool Checked { get; set; }

		public bool Disabled { get; set; }
	}
}

E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Models/Routes/SearchRouteFormModel.cs
namespace ETicketSystem.Web.Models.Routes
{
	using Common.Constants;
	using Microsoft.AspNetCore.Mvc.Rendering;
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public class SearchRouteFormModel
    {
		[Display(Name = WebConstants.FieldDisplay.StartDestination)]
		public int StartTown { get; set; }

		[Display(Name = WebConstants.FieldDisplay.EndDestination)]
		public int EndTown { get; set; }

		[DataType(DataType.Date)]
		public DateTime Date { get; set; }

		[Display(Name = WebConstants.FieldDisplay.Company)]
		public string CompanyId { get; set; }

		public IEnumerable<SelectListItem> Towns { get; set; }

		public IEnumerable<SelectListItem> Companies { get; set; }
	}
}

E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Areas/Company/Controllers/RoutesController.cs
namespace ETicketSystem.Web.Areas.Company.Controllers
{
	using Common.Constants;
	using Common.Enums;
	using Data.Models;
	using Microsoft.AspNetCore.Identity;
	using Microsoft.AspNetCore.Mvc;
	using Microsoft.AspNetCore.Mvc.Rendering;
	using Models.Routes;
	using Services.Company.Contracts;
	using Services.Contracts;
	using System;
	using System.Collections.Generic;
	using Web.Infrastructure.Extensions;
	using Web.Models.Pagination;

	public class RoutesController : BaseCompanyController
    {
		private readonly ICompanyRouteService routes;

		private readonly ICompanyService companies;

		private readonly IStationService stations;

		private readonly UserManager<User> userManager;

		public RoutesController(ICompanyRouteService routes, ITownService towns, UserManager<User> userManager, ICompanyService companies, IStationService stations)
			:base(towns)
		{
			this.routes = routes;
			this.userManager = userManager;
			this.companies = companies;
			this.stations = stations;
		}

		[Route(WebConstants.Routing.AllCompanyRoutes)]
		public IActionResult All(int startTown, int endTown, DateTime? date, int page = 1)
		{
			if (page < 1)
			{
				return RedirectToAction(nameof(All), new { startTown, endTown, date = date.HasValue ? date.Value.ToYearMonthDayFormat() : null, page = 1 });
			}

			var companyId = this.userManager.GetUserId(User);

			var routes = this.routes.All(startTown,endTown, date, companyId, page, WebConstants.Pagination.CompanyRoutesListing);

			var routesPagination = new PaginationViewModel()
			{
				Action = nameof(All),
				Controller = WebConstants.Controller.Routes,
				CurrentPage = page,
				PageSize = WebConstants.Pagination.CompanyRoutesListing,
				TotalElements = this.routes.TotalRoutes(startTown,endTown,date,companyId)
			};

			if (page > routesPagination.TotalPages && routesPagination.TotalPages != 0)
			{
				return RedirectToAction(nameof(All), new { startTown, endTown, date = date.HasValue ? date.Value.ToYearMonthDayFormat() : null, page = routesPagination.TotalPages });
			}

			return View(new AllRoutes()
			{
				Date = date,
				EndTown = endTown,
				StartTown = startTown,
				Pagination = routesPagination,
				Routes = routes.Routes,
				Towns = this.GenerateSelectListTowns()
			});
		}

		[Route(WebConstants.Routing.AddCompanyRoute)]
		public IActionResult Add()
		{
			var companyId = this.userManager.GetUserId(User);

			if (!this.companies.IsApproved(companyId))
			{
				this.GenerateAlertMessage(WebConstants.Message.CompanyNotApproved, Alert.Warning);

				return this.RedirectToAction(nameof(All));
			}

			if (this.companies.IsBlocked(companyId))
			{
				this.GenerateAlertMessage(WebConstants.Message.AddRouteCompanyBlocked, Alert.Warning);

				return this.RedirectToAction(nameof(All));
			}

			var townsWithStationsList = this.GenerateTownStationsSelectListItems();

			return View(new RouteFormModel()
			{
				TownsStations = townsWithStationsList
			});
		}

		[HttpPost]
		[Route(WebConstants.Routing.AddCompanyRoute)]
		public IActionResult Add(RouteFormModel model)
		{
			var companyId = this.userManager.GetUserId(User);

			if (!this.companies.IsApproved(companyId))
			{
				this.GenerateAlertMessage(WebConstants.Message.CompanyNotApproved, Alert.Warning);

				return this.RedirectToAction(nameof(All));
			}

			if (this.companies.IsBlocked(companyId))
			{
				this.GenerateAlertMessage(WebConstants.Message.AddRouteCompanyBlocked, Alert.Warning);

				return this.RedirectToAction(nameof(All));
			}

			if (!this.stations.StationExist(model.StartStation) || !this.stations.StationExist(model.EndStation))
			{
				this.GenerateAlertMessage(WebConstants.Message.InvalidStation, Alert.Warning);

				return this.RedirectToAction(nameof(All));
			}

			if (model.StartStation == model.EndStation || this.stations.AreStationsInSameTown(model.StartStation, model.EndStation))
			{
				ModelState.AddModelError(string.Empty,WebConstants.Message.StartStationEqualToEndStation);
				model.TownsStations = this.GenerateTownStationsSelectListItems();
				return View(model);
			}

			if (!ModelState.IsValid)
			{
                model.TownsStations = this.GenerateTownStationsSelectListItems();

				return View(model);
			}

			var isAdded = this.routes.Add(model.StartStation, model.EndStation, model.DepartureTime.TimeOfDay, model.Duration, model.BusType, model.Price, companyId);

			if (!isAdded)
			{
				model.TownsStations = this.GenerateTownStationsSelectListItems();
				ModelState.AddModelError(string.Empty, WebConstants.Message.CompanyRouteDuplication);
				return View(model);
			}

			var startTownName = this.towns.GetTownNameByStationId(model.StartStation);
			var endTownName = this.towns.GetTownNameByStationId(model.EndStation);

			this.GenerateAlertMessage(string.Format(WebConstants.Message.RouteAdded, startTownName, endTownName), Alert.Success);

			return RedirectToAction(nameof(All));
		}

		[Route(WebConstants.Routing.EditCompanyRoute)]
		public IActionResult Edit(int id)
		{
			var companyId = this.userManager.GetUserId(User);

			if (!this.routes.IsRouteOwner(id,companyId))
			{
				this.GenerateAlertMessage(WebConstants.Message.InvalidRoute, Alert.Danger);

				return RedirectToAction(nameof(All));
			}

			if (!this.companies.IsApproved(companyId))
			{
				this.GenerateAlertMessage(WebConstants.Message.ChangeRouteCompanyNotApproved, Alert.Warning);

				return this.RedirectToAction(nameof(All));
			}

			if (this.companies.IsBlocked(companyId))
			{
				this.GenerateAlertMessage(WebConstants.Message.ChangeRouteCompanyBlocked, Alert.Warning);

				return this.RedirectToAction(nameof(All));
			}

			var routeToEdit = this.routes.GetRouteToEdit(companyId, id);

			if (routeToEdit == null)
			{
				this.GenerateAlertMessage(WebConstants.Message.InvalidRoute, Alert.Danger);

				return RedirectToAction(nameof(All));
			}

			var startTownName = this.towns.GetTownNameByStationId(routeToEdit.StartStationId);
			var endTownName = this.towns.GetTownNameByStationId(routeToEdit.EndStationId);

			if (this.routes.HasReservedTickets(id, companyId))
			{
				this.GenerateAlertMessage(string.Format(WebConstants.Message.EditRouteWithTickets, startTownName, endTownName), Alert.Danger);

				return RedirectToAction(nameof(All));
			}

			return View(new RouteFormModel()
			{
				StartStation = routeToEdit.StartStationId,
				EndStation = routeToEdit.EndStationId,
				DepartureTime = routeToEdit.DepartureTime,
				Duration = routeToEdit.Duration,
				BusType = routeToEdit.BusType,
				Price = routeToEdit.Price,
				IsEdit = true,
				TownsStations = this.GenerateTownStationsSelectListItems()
			});
		}

		[HttpPost]
		[Route(WebConstants.Routing.EditCompanyRoute)]
		public IActionResult Edit(RouteFormModel model, int id)
		{
			var companyId = this.userManager.GetUserId(User);

			if (!this.routes.IsRouteOwner(id, companyId))
			{
				this.GenerateAlertMessage(WebConstants.Message.InvalidRoute, Alert.Danger);

				return RedirectToAction(nameof(All));
			}

			if (!this.companies.IsApproved(companyId))
			{
				this.GenerateAlertMessage(WebConstants.Message.ChangeRouteCompanyNotApproved, Alert.Warning);
				return this.RedirectToAction(nameof(All));
			}

			if (this.companies.IsBlocked(companyId))
			{
				this.GenerateAlertMessage(WebConstants.Message.ChangeRouteCompanyBlocked, Alert.Warning);
				return this.RedirectToAction(nameof(All));
			}

			if (!ModelState.IsValid)
			{
				model.TownsStations = this.GenerateTownStationsSelectListItems();
				model.IsEdit = true;
				return View(model);
			}

			var alreadyExists = this.routes.RouteAlreadyExist(id,model.StartStation, model.EndStation, model.DepartureTime.TimeOfDay, companyId);

			if (alreadyExists)
			{
				model.TownsStations = this.GenerateTownStationsSelectListItems();
				model.IsEdit = true;
				ModelState.AddModelError(string.Empty, WebConstants.Message.CompanyRouteDuplication);
				return View(model);
			}

			var startTownName = this.towns.GetTownNameByStationId(model.StartStation);
			var endTownName = this.towns.GetTownNameByStationId(model.EndStation);

			if (this.routes.HasReservedTickets(id, companyId))
			{
				this.GenerateAlertMessage(string.Format(WebConstants.Message.EditRouteWithTickets, startTownName, endTownName), Alert.Danger);

				return RedirectToAction(nameof(All));
			}

			var success = this.routes.Edit(id,model.StartStation,model.EndStation, model.DepartureTime.TimeOfDay, model.Duration, model.BusType, model.Price, companyId);

			if (!success)
			{
				this.GenerateAlertMessage(WebConstants.Message.InvalidRoute, Alert.Danger);

				return RedirectToAction(nameof(All));
			}

			this.GenerateAlertMessage(string.Format(WebConstants.Message.RouteEdited, startTownName, endTownName), Alert.Success);

			return RedirectToAction(nameof(All));
		}

		[Route(WebConstants.Routing.ChangeCompanyRouteStatus)]
		public IActionResult ChangeStatus(int id)
		{
			var companyId = this.userManager.GetUserId(User);

			if (!this.routes.IsRouteOwner(id, companyId))
			{
				this.GenerateAlertMessage(WebConstants.Message.InvalidRoute, Alert.Danger);

				return RedirectToAction(nameof(All));
			}

			if (!this.companies.IsApproved(companyId))
			{
				this.GenerateAlertMessage(WebConstants.Message.ChangeRouteCompanyNotApproved, Alert.Warning);
				return this.RedirectToAction(nameof(All));
			}

			if (this.companies.IsBlocked(companyId))
			{
				this.GenerateAlertMessage(WebConstants.Message.ChangeRouteCompanyBlocked, Alert.Warning);
				return this.RedirectToAction(nameof(All));
			}

			var routeInfo = this.routes.GetRouteBaseInfo(id, companyId);

			if (this.routes.HasReservedTickets(id, companyId))
			{
				this.GenerateAlertMessage(string.Format(WebConstants.Message.DeactivateRouteWithTickets, routeInfo.StartStationTownName, routeInfo.EndStationTownName), Alert.Danger);

				return RedirectToAction(nameof(All));
			}

			var success = this.routes.ChangeStatus(id, companyId);

E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Controllers/CompaniesController.cs
namespace ETicketSystem.Web.Controllers
{
	using Common.Constants;
	using Common.Enums;
	using Microsoft.AspNetCore.Mvc;
	using Models.Companies;
	using Models.Pagination;
	using Models.Reviews;
	using Models.Routes;
	using Services.Contracts;

	public class CompaniesController : BaseController
    {
		private readonly ICompanyService companies;

		private readonly IReviewService reviews;

		public CompaniesController(ICompanyService companies,ITownService towns, IReviewService reviews)
			:base(towns)
		{
			this.companies = companies;
			this.reviews = reviews;
		}

		public IActionResult All(string searchTerm, int page = 1)
		{
			if (page < 1)
			{
				return RedirectToAction(nameof(All),new { searchTerm = searchTerm});
			}

			var companiesPagination = new PaginationViewModel()
			{
				CurrentPage = page,
				PageSize = WebConstants.Pagination.CompaniesPageSize,
				TotalElements = this.companies.TotalCompanies(searchTerm),
				SearchTerm = searchTerm,
				Action = nameof(All),
				Controller = WebConstants.Controller.Companies
			};

			if (page > companiesPagination.TotalPages && companiesPagination.TotalPages != 0)
			{
				return RedirectToAction(nameof(All), new { searchTerm = searchTerm,page = companiesPagination.TotalPages });
			}

			return View(new AllCompanies()
			{
				Companies = this.companies.All(page,searchTerm, WebConstants.Pagination.CompaniesPageSize),
				Pagination = companiesPagination
			});
		}

		public IActionResult Details(string id, int page = 1)
		{
			var company = this.companies.CompanyDetails(id);

			if (company == null)
			{
				this.GenerateAlertMessage(string.Format(WebConstants.Message.NonExistingEntity,nameof(WebConstants.Entity.Company),id), Alert.Warning);

				return RedirectToAction(nameof(All));
			}

			if (page < 1)
			{
				return RedirectToAction(nameof(Details), new { id = id, page = 1 });
			}

			var reviewsPagination = new PaginationViewModel()
			{
				Action = nameof(Details),
				Controller = WebConstants.Controller.Companies,
				CurrentPage = page,
				PageSize = WebConstants.Pagination.CompanyReviewsListing,
				TotalElements = this.reviews.TotalReviews(id)
			};

			if (page > reviewsPagination.TotalPages && reviewsPagination.TotalPages != 0)
			{
				return RedirectToAction(nameof(Details), new { id = id, page = reviewsPagination.TotalPages });
			}

			return View(new CompanyDetails()
			{
				Company = company,
				SearchForm = new SearchRouteFormModel()
				{
					CompanyId = id,
					Towns = this.GenerateSelectListTowns()
				},
				ReviewForm = new ReviewFormModel()
				{
					CompanyId = id
				},
				Reviews = new AllCompanyReviews()
				{
					Reviews = this.reviews.All(id,page,WebConstants.Pagination.CompanyReviewsListing),
					Pagination = reviewsPagination
				}
			});
		}
    }
}

E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Views/Routes/BookTicket.cshtml
@model BookTicketFormModel

@{
    ViewData["Title"] = "Book Ticket";
}

<environment include="Development">
    <link rel="stylesheet" href="~/css/route/book-ticket.css" />
</environment>

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />

<a class="btn btn-primary" href="/routes/search?StartTown=@Model.StartTownId&EndTown=@Model.EndTownId&Date=@Model.DepartureDateTime.ToYearMonthDayFormat()@(string.IsNullOrEmpty(Model.CompanyId) ? string.Empty : $"&CompanyId={Model.CompanyId}")">Back</a>

<div class="col-md-6 route-info-container">
    <div>
        <i class="fa fa-calendar" aria-hidden="true"></i>
        <strong>Departure: </strong>@Model.DepartureDateTime
    </div>
    <div>
        <i class="fa fa-location-arrow" aria-hidden="true"></i>
        <strong>Route: </strong>@Model.StartStation - @Model.EndStation
    </div>
    <div>
        <i class="fa fa-clock-o" aria-hidden="true"></i>
        <strong>Duration: </strong>@Model.Duration.Hours hours and @Model.Duration.Minutes minutes
    </div>
    <div>
        <i class="fa fa-building" aria-hidden="true"></i>
        <strong>Company: </strong>@Model.CompanyName
    </div>
</div>

<div class="container-fluid col-md-12 col-lg-12 col-sm-12">
    <div class="form-container">
        @Html.Partial("_BookTicketForm", Model)
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Views/Routes/Search.cshtml
@model SearchedRoutes

@{
    ViewData["Title"] = "Search Routes";
}

<environment include="Development">
    <link rel="stylesheet" href="~/css/route/list-routes.css" />
    <link rel="stylesheet" href="~/css/route/horizontal-search-form.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
</environment>

<h2 class="text-center">@ViewData["Title"]</h2>

<div class="container-fluid">
    <div class="row search-container">
        <form method="get" asp-controller="Routes" asp-action="Search" class="search-form col-md-12">
            <div class="text-danger text-center form-errors" hidden>
                Start destination and end destination cannot be equal!
            </div>
            <div class="form-fields row">
                <div class="form-group col-md-3">
                    <label asp-for="StartTown"></label>
                    <select asp-for="StartTown" asp-items="Model.Towns" class="form-control start-town" required></select>
                    <span asp-validation-for="StartTown" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="EndTown"></label>
                    <select asp-for="EndTown" asp-items="Model.Towns" class="form-control end-town" required></select>
                    <span asp-validation-for="EndTown" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="Date"></label>
                    <input asp-for="Date" min="@DateTime.UtcNow.ToLocalTime().ToString("yyyy-MM-dd")" class="form-control"/>
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="CompanyId"></label>
                    <select asp-for="CompanyId" asp-items="Model.Companies" class="form-control end-town"></select>
                    <span asp-validation-for="CompanyId" class="text-danger"></span>
                </div>
            </div>
            <input type="submit" value="Search" class="btn btn-success" onclick="checkTownsEquality()" />
        </form>
    </div>
</div>
<hr />

@if (Model.Routes.Count() == 0)
{
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Oooops!</h4>
        <p>We couldn't find any routes matching your criteria!</p>
        <hr>
        <p class="mb-0">Just have another try or contact us so we can help you immediately!</p>
    </div>
}
else
{
    <div class="container-fluid ticket-list">
        @foreach (var route in Model.Routes)
        {
            <div class="route-container row">
                <div class="col-md-2 col-sm-2 col-lg-2">
                    <a class="company-name" asp-controller="Companies" asp-action="Details" asp-route-id="@route.CompanyId">@route.CompanyName</a>
                    <a asp-controller="Companies" asp-action="Details" asp-route-id="@route.CompanyId">
                        @if (route.CompanyLogo == null)
                        {
                            <img class="img-responsive" src="~/images/common/no-logo.png" alt="@route.CompanyName" />
                        }
                        else
                        {
                            <img class="img-responsive" src="@route.CompanyLogo.ConvertBytesToImage()" alt="@route.CompanyName" />
                        }
                    </a>
                </div>
                <div class="col-md-2 col-sm-2 col-lg-2">
                    <span class="departure-time">@route.DepartureTime.ToHoursAndMinutes()</span>
                </div>
                <div class="stations col-md-4 col-sm-4 col-lg-4 text-center">
                    <span>@route.StartStation > @route.EndStation</span>
                    <span>
                        (@route.Duration.Hours Hours @(route.Duration.Minutes == 0 ? string.Empty : $"{route.Duration.Minutes} Minutes"))
                    </span>
                </div>
                <div class="price col-md-2 col-sm-2 col-lg-2">
                    <span>@route.Price.ToFormatedPrice() $</span>
                </div>
                <div class="tickets col-md-2 col-sm-2 col-lg-2">
                    <div class="seats-info">@route.ReservedTickets / @route.TotalBusSeats</div>
                    <form method="get" asp-controller="Routes" asp-action="BookTicket" asp-route-id="@route.Id" asp-route-departureTime="@route.DepartureTime.ToHoursAndMinutes()" asp-route-date="@Model.Date.ToYearMonthDayFormat()" asp-route-companyId="@Model.CompanyId">
                        <input class="btn btn@(route.ReservedTickets == route.TotalBusSeats ? "-danger disabled" : "-success")" type="submit" value="@(route.ReservedTickets == route.TotalBusSeats ? "Sold out" : "Tickets")" />
                    </form>
                </div>
            </div>
            <hr />
        }
    </div>

    <div class="container-fluid text-center">
        <ul class="pagination">
            <li class="page-item @(1 == Model.Pagination.CurrentPage ? "blocked":string.Empty)">
                <a class="page-link" asp-controller="@Model.Pagination.Controller" asp-action="@Model.Pagination.Action" asp-route-startTown="@Model.StartTown" asp-route-endTown="@Model.EndTown" asp-route-companyId="@Model.CompanyId" asp-route-date="@Model.Date.ToYearMonthDayFormat()" asp-route-page="@Model.Pagination.PreviousPage">Previous</a>
            </li>
            @for (int i = 1; i <= Model.Pagination.TotalPages; i++)
            {
                <li class="page-item @(i == Model.Pagination.CurrentPage ? "active blocked":string.Empty)">
                    <a class="page-link" asp-controller="@Model.Pagination.Controller" asp-action="@Model.Pagination.Action" asp-route-startTown="@Model.StartTown" asp-route-endTown="@Model.EndTown" asp-route-companyId="@Model.CompanyId" asp-route-date="@Model.Date.ToYearMonthDayFormat()" asp-route-page="@i">@i</a>
                </li>
            }
            <li class="page-item @(Model.Pagination.TotalPages == Model.Pagination.CurrentPage ? "blocked":string.Empty)">
                <a class="page-link" asp-controller="@Model.Pagination.Controller" asp-action="@Model.Pagination.Action" asp-route-startTown="@Model.StartTown" asp-route-endTown="@Model.EndTown" asp-route-companyId="@Model.CompanyId" asp-route-date="@Model.Date.ToYearMonthDayFormat()" asp-route-page="@Model.Pagination.NextPage">Next</a>
            </li>
        </ul>
    </div>
}

@section Scripts {
    <script type="text/javascript" src="~/js/route/search-form-validation.js"></script>
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Views/Routes/_BookTicketForm.cshtml
@model BookTicketFormModel

@{
    ViewData["Title"] = "Book ticket";
}

<form method="post" class="col-md-12">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="DepartureDateTime" />
    <input type="hidden" asp-for="Duration" />
    <input type="hidden" asp-for="RouteId" />
    <input type="hidden" asp-for="BusSeats" />
    <input type="hidden" asp-for="StartStation" />
    <input type="hidden" asp-for="EndStation" />
    <input type="hidden" asp-for="CompanyName" />
    <input type="hidden" asp-for="CompanyId" />
    <input type="hidden" asp-for="StartTownId" />
    <input type="hidden" asp-for="EndTownId" />
    <div class="bus">
        <ol class="cabin fuselage">
            @for (int r = Model.BusSeats / 10; r > 0; r--)
            {
                <li class="row">
                    <ol class="seats">
                        @for (int c = r; c <= Model.BusSeats; c += Model.BusSeats / 10)
                        {
                            <li class="seat">
                                <input type="checkbox" class="@(Model.Seats[c-1].Disabled ? "disabled" : string.Empty)" asp-for="@Model.Seats[c-1].Checked" />
                                <input type="hidden" asp-for="@Model.Seats[c-1].Text" />
                                <input type="hidden" asp-for="@Model.Seats[c-1].Value" />
                                <input type="hidden" asp-for="@Model.Seats[c-1].Disabled" />
                                <label class="@(Model.Seats[c-1].Disabled ? "disabled" : string.Empty)" asp-for="@Model.Seats[c-1].Checked">@Model.Seats[c-1].Text</label>
                            </li>
                        }
                    </ol>
                </li> 
            }
        </ol>
    </div>
    <input type="submit" value="Buy" class="btn btn-success col-md-2 col-md-offset-5 buy" />
</form>