E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Areas/Company/Models/Profile/EditCompanyProfileFormModel.cs
namespace ETicketSystem.Web.Areas.Company.Models.Profile
{
	using Common.Constants;
	using Microsoft.AspNetCore.Http;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public class EditCompanyProfileFormModel : IValidatableObject
    {
		[Required]
		[StringLength(DataConstants.User.UsernameMaxLength, ErrorMessage = WebConstants.Message.UsernameLength, MinimumLength = DataConstants.User.UsernameMinLength)]
		public string Username { get; set; }

		[Required]
		[RegularExpression(WebConstants.RegexPattern.Email, ErrorMessage = WebConstants.Message.InvalidEmail)]
		public string Email { get; set; }

		public byte[] CurrentLogo { get; set; }

		public IFormFile Logo { get; set; }

		[Required]
		[StringLength(DataConstants.Company.DescriptionMaxLength, ErrorMessage = WebConstants.Message.CompanyDescriptionLength, MinimumLength = DataConstants.Company.DescriptionMinLength)]
		public string Description { get; set; }

		[StringLength(DataConstants.User.PasswordMaxLength, ErrorMessage = WebConstants.Message.PasswordLength, MinimumLength = DataConstants.User.PasswordMinLength)]
		[DataType(DataType.Password)]
		public string Password { get; set; }

		[StringLength(DataConstants.User.PasswordMaxLength, ErrorMessage = WebConstants.Message.PasswordLength, MinimumLength = DataConstants.User.PasswordMinLength)]
		[DataType(DataType.Password)]
		[Display(Name = WebConstants.FieldDisplay.NewPassword)]
		public string NewPassword { get; set; }

		[Required]
		[RegularExpression(WebConstants.RegexPattern.Phone, ErrorMessage = WebConstants.Message.PhoneNumberFormat)]
		[Display(Name = WebConstants.FieldDisplay.PhoneNumber)]
		public string PhoneNumber { get; set; }

		public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
		{
			if (this.Logo != null)
			{
				if (this.Logo.Length > DataConstants.Company.LogoMaxLength)
				{
					yield return new ValidationResult(WebConstants.Message.LogoMaxLength);
				}

				if (!this.Logo.FileName.EndsWith(WebConstants.PictureFormat.Jpg)
					&& !this.Logo.FileName.EndsWith(WebConstants.PictureFormat.Bmp)
					&& !this.Logo.FileName.EndsWith(WebConstants.PictureFormat.Png))
				{
					yield return new ValidationResult(WebConstants.Message.LogoAvailableFormats);
				}
			}
		}
	}
}

E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Models/Users/EditUserProfileFormModel.cs
namespace ETicketSystem.Web.Models.Users
{
	using Common.Constants;
	using System.ComponentModel.DataAnnotations;

	public class EditUserProfileFormModel
    {
		[Required]
		[RegularExpression(WebConstants.RegexPattern.Email, ErrorMessage = WebConstants.Message.InvalidEmail)]
		public string Email { get; set; }

		[Required]
		[StringLength(DataConstants.User.UsernameMaxLength, ErrorMessage = WebConstants.Message.UsernameLength, MinimumLength = DataConstants.User.UsernameMinLength)]
		public string Username { get; set; }

		[StringLength(DataConstants.User.PasswordMaxLength, ErrorMessage = WebConstants.Message.PasswordLength, MinimumLength = DataConstants.User.PasswordMinLength)]
		[DataType(DataType.Password)]
		public string Password { get; set; }

		[StringLength(DataConstants.User.PasswordMaxLength, ErrorMessage = WebConstants.Message.PasswordLength, MinimumLength = DataConstants.User.PasswordMinLength)]
		[DataType(DataType.Password)]
		[Display(Name = WebConstants.FieldDisplay.NewPassword)]
		public string NewPassword { get; set; }
	}
}

E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Models/Users/UserTickets.cs
namespace ETicketSystem.Web.Models.Users
{
	using Common.Constants;
	using Microsoft.AspNetCore.Mvc.Rendering;
	using Pagination;
	using Services.Models.Ticket;
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public class UserTickets
    {
		public IEnumerable<UserTicketListingServiceModel> Tickets { get; set; }

		public PaginationViewModel Pagination { get; set; }

		[Display(Name = WebConstants.FieldDisplay.StartDestination)]
		public int StartTown { get; set; }

		[Display(Name = WebConstants.FieldDisplay.EndDestination)]
		public int EndTown { get; set; }

		[DataType(DataType.Date)]
		[DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)]
		public DateTime? Date { get; set; }

		[Display(Name = WebConstants.FieldDisplay.Company)]
		public string CompanyId { get; set; }

		public IEnumerable<SelectListItem> Towns { get; set; }

		public IEnumerable<SelectListItem> Companies { get; set; }
	}
}

E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Areas/Company/Controllers/ProfileController.cs
namespace ETicketSystem.Web.Areas.Company.Controllers
{
    using Common.Constants;
    using Common.Enums;
    using Data.Models;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Models.Profile;
    using Services.Contracts;
    using System.Linq;
    using System.Threading.Tasks;
    using Web.Infrastructure.Extensions;

    public class ProfileController : BaseCompanyController
    {
		private readonly IUserService users;

		private readonly UserManager<User> userManager;

		public ProfileController(IUserService users, UserManager<User> userManager)
		{
			this.users = users;
			this.userManager = userManager;
		}

		[Route(WebConstants.Routing.CompanyProfile)]
		public IActionResult Index(string id)
		{
			var companyId = this.userManager.GetUserId(User);

			if (companyId != id)
			{
				this.GenerateAlertMessage(WebConstants.Message.NotProfileOwner, Alert.Danger);

				return RedirectToHome();
			}

			return View(this.users.GetCompanyProfileDetails(companyId));
		}

		[Route(WebConstants.Routing.EditCompanyProfile)]
		public IActionResult Edit(string id)
		{
			var company = this.users.GetCompanyUserProfileToEdit(id);

			if (company == null)
			{
				this.GenerateAlertMessage(string.Format(WebConstants.Message.NonExistingEntity,WebConstants.Entity.Company, id), Alert.Danger);

				return RedirectToHome();
			}

			if (this.userManager.GetUserId(User) != id)
			{
				this.GenerateAlertMessage(string.Format(WebConstants.Message.NotProfileOwner, id), Alert.Danger);

				return RedirectToHome();
			}

			return View(new EditCompanyProfileFormModel()
			{
				Username = company.Username,
				Email = company.Email,
				Description = company.Description,
				CurrentLogo =company.Logo,
				PhoneNumber = company.PhoneNumber
			});
		}

		[HttpPost]
		[Route(WebConstants.Routing.EditCompanyProfile)]
		public async Task<IActionResult> Edit(string id, EditCompanyProfileFormModel profile)
		{
			if (!ModelState.IsValid)
			{
				profile.CurrentLogo = this.users.GetCompanyLogo(id);

				return View(profile);
			}

			if (!this.users.UserExists(id) || this.userManager.GetUserId(User) != id)
			{
				return BadRequest();
			}

			var errors = await this.users.EditCompanyAsync(id,profile.Username,profile.Email,profile.NewPassword,profile.Password,profile.Description,profile.Logo.GetFormFileBytes(), profile.PhoneNumber);

			if (errors.Count() != 0)
			{
				foreach (var error in errors)
				{
					ModelState.AddModelError("", error.Description);
				}

				profile.CurrentLogo = this.users.GetCompanyLogo(id);

				return View(profile);
			}

			this.GenerateAlertMessage(WebConstants.Message.ProfileEdited, Alert.Success);

			return RedirectToAction(nameof(Index), new { id });
		}
	}
}

E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Controllers/TicketsController.cs
namespace ETicketSystem.Web.Controllers
{
	using Common.Constants;
	using Common.Enums;
	using Data.Models;
	using Microsoft.AspNetCore.Authorization;
	using Microsoft.AspNetCore.Identity;
	using Microsoft.AspNetCore.Mvc;
	using Services.Contracts;

	[Authorize]
	public class TicketsController : BaseController
    {
		private readonly ITicketService tickets;

		private readonly UserManager<User> userManager;

		public TicketsController(ITicketService tickets, UserManager<User> userManager)
		{
			this.tickets = tickets;
			this.userManager = userManager;
		}

		public IActionResult Cancel(int id)
		{
			var userId = this.userManager.GetUserId(User);

			if (!this.tickets.TicketExists(id) 
				|| !this.tickets.IsTicketOwner(id, userId)
				|| this.tickets.IsCancelled(id))
			{
				this.GenerateAlertMessage(string.Format(WebConstants.Message.NonExistingEntity,WebConstants.Entity.Ticket,id), Alert.Danger);
				return RedirectToAction(WebConstants.Action.MyTickets,WebConstants.Controller.Users,new { id = userId});
			}

			bool success = this.tickets.CancelTicket(id, userId);

			if (!success)
			{
				this.GenerateAlertMessage(WebConstants.Message.TicketCancelationDenied, Alert.Warning);
				return RedirectToAction(WebConstants.Action.MyTickets, WebConstants.Controller.Users, new { id = userId });
			}

			this.GenerateAlertMessage(WebConstants.Message.TicketCancelationSuccess,Alert.Success);

			return RedirectToAction(WebConstants.Action.MyTickets, WebConstants.Controller.Users, new { id = userId });
		}

		public IActionResult Download(int id)
		{
			var userId = this.userManager.GetUserId(User);
			var ticket = this.tickets.GetPdfTicket(id, userId);

			if (ticket == null)
			{
				this.GenerateAlertMessage(WebConstants.Message.InvalidTicket, Alert.Danger);
				return RedirectToAction(WebConstants.Action.MyTickets,WebConstants.Controller.Users, new { id = this.userManager.GetUserId(User) });
			}

			var ticketInfo = this.tickets.GetTicketDownloadInfo(id, userId);

			return File(ticket, WebConstants.ContentType.Pdf, string.Format(WebConstants.Pdf.TicketName,ticketInfo.StartTown, ticketInfo.EndTown, string.Concat(ticketInfo.DepartureTime)));
		}
	}
}

E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Controllers/UsersController.cs
namespace ETicketSystem.Web.Controllers
{
	using Common.Constants;
	using Common.Enums;
	using Data.Models;
	using Infrastructure.Extensions;
	using Microsoft.AspNetCore.Authorization;
	using Microsoft.AspNetCore.Identity;
	using Microsoft.AspNetCore.Mvc;
	using Microsoft.AspNetCore.Mvc.Rendering;
	using Models.Pagination;
	using Models.Users;
	using Services.Contracts;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Threading.Tasks;

	[Authorize]
	public class UsersController : BaseController
    {
		private readonly IUserService users;

		private readonly ITicketService tickets;

		private readonly ICompanyService companies;

		private readonly UserManager<User> userManager;

		public UsersController(IUserService users, ITownService towns, UserManager<User> userManager, ITicketService tickets, ICompanyService companies)
			:base(towns)
		{
			this.users = users;
			this.userManager = userManager;
			this.tickets = tickets;
			this.companies = companies;
		}

		public async Task<IActionResult> Profile(string id)
		{
			if (this.userManager.GetUserId(User) != id)
			{
				this.GenerateAlertMessage(WebConstants.Message.NotProfileOwner, Alert.Danger);

				return RedirectToHome();
			}

			var user = await this.users.GetRegularUserProfileDetailsAsync(id);

			if (user == null)
			{
				this.GenerateAlertMessage(string.Format(WebConstants.Message.NonExistingEntity,WebConstants.Entity.User, id), Alert.Danger);
				return RedirectToHome();
			}

			return View(user);
		}

		[Route(WebConstants.Routing.EditUser)]
		public IActionResult EditUser(string id)
		{
			if (!this.users.UserExists(id))
			{
				this.GenerateAlertMessage(string.Format(WebConstants.Message.NonExistingEntity,WebConstants.Entity.User, id), Alert.Danger);

				return RedirectToHome();
			}

			if (this.userManager.GetUserId(User) != id)
			{
				this.GenerateAlertMessage(string.Format(WebConstants.Message.NotProfileOwner, id), Alert.Danger);

				return RedirectToHome();
			}

			var user = this.users.GetRegularUserProfileToEdit(id);

			return View(new EditUserProfileFormModel()
			{
				Username = user.Username,
				Email = user.Email
			});
		}

		[HttpPost]
		[Route(WebConstants.Routing.EditUser)]
		public async Task<IActionResult> EditUser(string id, EditUserProfileFormModel profile)
		{
			if (!ModelState.IsValid)
			{
				return View(profile);
			}

			if (!this.users.UserExists(id) || this.userManager.GetUserId(User) != id)
			{
				return BadRequest();
			}

			var errors = await this.users.EditRegularUserAsync(id, profile.Username, profile.Email, profile.NewPassword, profile.Password);

			if (errors.Count() != 0)
			{
				foreach (var error in errors)
				{
					ModelState.AddModelError("", error.Description);
				}

				return View(profile);
			}

			this.GenerateAlertMessage(WebConstants.Message.ProfileEdited, Alert.Success);

			return RedirectToAction(nameof(Profile), new { id = id });
		}

		[Route(WebConstants.Routing.UserTickets)]
		public IActionResult MyTickets(string id, int startTown, int endTown, string companyId, DateTime? date, int page = 1)
		{
			if (this.userManager.GetUserId(User) != id)
			{
				this.GenerateAlertMessage(WebConstants.Message.NotProfileOwner, Alert.Danger);

				return RedirectToHome();
			}

			if (page < 1)
			{
				return RedirectToAction(nameof(MyTickets), new { id = id, startTown = startTown, endTown = endTown, companyId = companyId, date = (date.HasValue ? date.Value.ToYearMonthDayFormat() : null), page = 1 });
			}

			var tickets = this.tickets.GetUserTickets(id, startTown, endTown, companyId, date, page, WebConstants.Pagination.UserTicketsPageSize);

			var pagination = new PaginationViewModel()
			{
				Action = nameof(MyTickets),
				Controller = WebConstants.Controller.Users,
				CurrentPage = page,
				PageSize = WebConstants.Pagination.UserTicketsPageSize,
				TotalElements = this.tickets.UserTicketsCount(id, startTown, endTown, companyId, date)
			};

			if (page > pagination.TotalPages && pagination.TotalPages != 0)
			{
				return RedirectToAction(nameof(MyTickets), new { id = id, startTown = startTown, endTown = endTown, companyId = companyId, date = (date.HasValue ? date.Value.ToYearMonthDayFormat() : null), page = pagination.TotalPages });
			}

			var selectListTowns = this.GenerateSelectListTowns();
			selectListTowns.First().Disabled = false;

			return View(new UserTickets()
			{
				Tickets = tickets,
				Pagination = pagination,
				Towns = selectListTowns,
				Companies = this.GenerateSelectListCompanies(),
				CompanyId = companyId,
				Date = date,
				StartTown = startTown,
				EndTown = endTown
			});
		}

		private List<SelectListItem> GenerateSelectListCompanies()
		{
			var list = new List<SelectListItem>();
			var companies = this.companies.GetCompaniesSelectListItems();

			list.Add(new SelectListItem()
			{
				Text = WebConstants.SelectListDefaultItem.All,
				Value = string.Empty,
				Selected = true
			});

			foreach (var c in companies)
			{
				list.Add(new SelectListItem()
				{
					Text = c.Name,
					Value = c.Id.ToString()
				});
			}

			return list;
		}
	}
}

E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Views/Users/EditUser.cshtml
@model EditUserProfileFormModel

@{
    ViewData["Title"] = "Edit";
    Layout = "_UserProfileLayout";
}
<h2 class="text-center">Edit Profile</h2>
<div class="container-fluid">
    <form method="post" class="col-md-6 col-md-offset-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Username"></label>
            <input asp-for="Username" class="form-control" />
            <span asp-validation-for="Username" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Email"></label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Password"></label>
            <input asp-for="Password" class="form-control" />
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="NewPassword"></label>
            <input asp-for="NewPassword" class="form-control" />
            <span asp-validation-for="NewPassword" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-success col-md-6 col-md-offset-3">Edit</button>
    </form>
</div>

E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Views/Users/MyTickets.cshtml
@model UserTickets

@{
    ViewData["Title"] = "My Tickets";
    Layout = "_UserProfileLayout";
}

<h2 class="text-center">@ViewData["Title"]</h2>

<div class="container-fluid">
    <div class="row search-container">
        <form method="get" asp-controller="Users" asp-action="MyTickets" class="search-form col-md-12">
            <div class="text-danger text-center form-errors" hidden>
                Start destination and end destination cannot be equal!
            </div>
            <div class="form-fields row">
                <div class="form-group col-md-3">
                    <label asp-for="StartTown"></label>
                    <select asp-for="StartTown" asp-items="Model.Towns" class="form-control start-town" required></select>
                    <span asp-validation-for="StartTown" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="EndTown"></label>
                    <select asp-for="EndTown" asp-items="Model.Towns" class="form-control end-town" required></select>
                    <span asp-validation-for="EndTown" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="Date"></label>
                    <input asp-for="Date" class="form-control" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="CompanyId"></label>
                    <select asp-for="CompanyId" asp-items="Model.Companies" class="form-control end-town"></select>
                    <span asp-validation-for="CompanyId" class="text-danger"></span>
                </div>
            </div>
            <input type="submit" value="Search" class="btn btn-success" onclick="checkTownsEquality()" />
            <a asp-controller="Users" asp-action="MyTickets" class="btn btn-primary">Clear</a>
        </form>
    </div>
</div>
<hr />

@if(Model.Tickets.Count() == 0)
{
    @Html.Partial("_NoResultsFoundMessageBox")
}
else
{
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Company</th>
                <th>Route</th>
                <th>Seat</th>
                <th>Departure time</th>
                <th>Price</th>
                <th>Download</th>
                <th>Cancellation</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var t in Model.Tickets)
            {
                <tr>
                    <td>@t.CompanyName</td>
                    <td>@t.Route</td>
                    <td>@t.SeatNumber</td>
                    <td>@t.DepartureTime</td>
                    <td>@t.Price.ToFormatedPrice() $</td>
                    <td>
                        <a asp-controller="Tickets" asp-action="Download" asp-route-id="@t.Id" class="btn btn-primary">Download</a>
                    </td>
                    <td>
                        @{  var timeSpan = t.DepartureTime - DateTime.UtcNow.ToLocalTime();}
                        @if (timeSpan.TotalMinutes >= WebConstants.Ticket.CancelationMinutesDifference)
                        {
                            <a asp-controller="Tickets" asp-action="Cancel" asp-route-id="@t.Id" class="btn btn-danger">Cancel</a>
                        }
                        else
                        {
                            <span class="success">N/A</span>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div class="container-fluid text-center">
        <ul class="pagination">
            <li class="page-item @(1 == Model.Pagination.CurrentPage ? "blocked":string.Empty)">
                <a class="page-link" asp-controller="@Model.Pagination.Controller" asp-action="@Model.Pagination.Action" asp-route-startTown="@Model.StartTown" asp-route-endTown="@Model.EndTown" asp-route-companyId="@Model.CompanyId" asp-route-date="@(Model.Date.HasValue ? Model.Date.Value.ToYearMonthDayFormat() : null)" asp-route-page="@Model.Pagination.PreviousPage">Previous</a>
            </li>
            @for (int i = 1; i <= Model.Pagination.TotalPages; i++)
            {
                <li class="page-item @(i == Model.Pagination.CurrentPage ? "active blocked":string.Empty)">
                    <a class="page-link" asp-controller="@Model.Pagination.Controller" asp-action="@Model.Pagination.Action" asp-route-startTown="@Model.StartTown" asp-route-endTown="@Model.EndTown" asp-route-companyId="@Model.CompanyId" asp-route-date="@(Model.Date.HasValue ? Model.Date.Value.ToYearMonthDayFormat() : null)" asp-route-page="@i">@i</a>
                </li>
            }
            <li class="page-item @(Model.Pagination.TotalPages == Model.Pagination.CurrentPage ? "blocked":string.Empty)">
                <a class="page-link" asp-controller="@Model.Pagination.Controller" asp-action="@Model.Pagination.Action" asp-route-startTown="@Model.StartTown" asp-route-endTown="@Model.EndTown" asp-route-companyId="@Model.CompanyId" asp-route-date="@(Model.Date.HasValue ? Model.Date.Value.ToYearMonthDayFormat() : null)" asp-route-page="@Model.Pagination.NextPage">Next</a>
            </li>
        </ul>
    </div>
}

E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Views/Users/Profile.cshtml
@model RegularUserProfileServiceModel

@{
    ViewData["Title"] = "Details";
    Layout = "_UserProfileLayout";
}

@Html.Partial("_RegularUserProfileInfo", Model)

E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Views/Users/_RegularUserProfileInfo.cshtml
@model RegularUserProfileServiceModel

<h2 class="text-center">Profile Info</h2>

<div class="profile-info">
    <div class="profile-fragment">
        <span><strong>Username: </strong></span>
        <span>@Model.Username</span>
    </div>
    <div class="profile-fragment">
        <span><strong>Name: </strong></span>
        <span>@Model.FirstName @Model.LastName</span>
    </div>
    <div class="profile-fragment">
        <span><strong>Email: </strong></span>
        <span>@Model.Email</span>
    </div>
    <div class="profile-fragment">
        <span><strong>Roles: </strong></span>
        <span>@(Model.Roles.Count() == 0 ? "None" : string.Join(", ", Model.Roles))</span>
    </div>
</div>