E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Areas/Admin/Models/AdminCompanies/AllCompanies.cs
namespace ETicketSystem.Web.Areas.Admin.Models.AdminCompanies
{
	using Common.Enums;
	using Services.Admin.Models;
	using System.Collections.Generic;
	using Web.Models.Pagination;

	public class AllCompanies
    {
		public IEnumerable<AdminCompanyListingServiceModel> Companies { get; set; }

		public CompanyStatus Filter { get; set; }

		public PaginationViewModel Pagination { get; set; }
    }
}

E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Areas/Admin/Controllers/AdminCompaniesController.cs
namespace ETicketSystem.Web.Areas.Admin.Controllers
{
	using Common.Constants;
	using Common.Enums;
	using Microsoft.AspNetCore.Mvc;
	using Models.AdminCompanies;
	using Services.Admin.Contracts;
	using System;
	using Web.Models.Pagination;

	public class AdminCompaniesController : BaseAdminController
    {
		private readonly IAdminCompanyService companies;

		public AdminCompaniesController(IAdminCompanyService companies)
		{
			this.companies = companies;
		}

		[Route(WebConstants.Routing.AdminAllCompanies)]
		public IActionResult All(CompanyStatus filter,int page = 1)
		{
			if (page < 1)
			{
				return RedirectToAction(nameof(All), new { filter = filter});
			}

			if (!Enum.IsDefined(typeof(CompanyStatus),filter))
			{
				filter = CompanyStatus.All;
				return RedirectToAction(nameof(All), new { filter = filter });
			}

			var companiesPagination = new PaginationViewModel()
			{
				Action = nameof(All),
				Controller = WebConstants.Controller.AdminCompanies,
				CurrentPage = page,
				PageSize = WebConstants.Pagination.AdminCompaniesListing,
				TotalElements = this.companies.TotalCompanies(filter.ToString()),
				SearchTerm = filter.ToString()
			};

			if (page > companiesPagination.TotalPages && companiesPagination.TotalPages != 0)
			{
				return RedirectToAction(nameof(All), new { page = companiesPagination.TotalPages, filter = filter });
			}

			return View(new AllCompanies()
			{
				Companies = this.companies.All(page, filter.ToString(), WebConstants.Pagination.AdminCompaniesListing),
				Pagination = companiesPagination,
				Filter = filter
			});
		}

		[Route(WebConstants.Routing.AdminApproveCompany)]
		public IActionResult Approve(string companyId, CompanyStatus filter, int page)
		{
			if (!this.companies.CompanyExists(companyId))
			{
				this.GenerateAlertMessage(string.Format(WebConstants.Message.NonExistingEntity,nameof(WebConstants.Entity.Company), companyId), Alert.Danger);
				return RedirectToAction(nameof(All));
			}

			var isApproved = this.companies.Approve(companyId);
			var companyName = this.companies.GetCompanyName(companyId);

			if (!isApproved)
			{
				this.GenerateAlertMessage(string.Format(WebConstants.Message.CompanyAlreadyApproved, companyName), Alert.Warning);
			}
			else
			{
				this.GenerateAlertMessage(string.Format(WebConstants.Message.CompanyApproved, companyName), Alert.Success);
			}

			return RedirectToAction(nameof(All), new { page = page, filter = filter});
		}

		[Route(WebConstants.Routing.AdminBlockCompany)]
		public IActionResult Block(string companyId, CompanyStatus filter, int page)
		{
			if (!this.companies.CompanyExists(companyId))
			{
				this.GenerateAlertMessage(string.Format(WebConstants.Message.NonExistingEntity, nameof(WebConstants.Entity.Company), companyId), Alert.Danger);
				return RedirectToAction(nameof(All));
			}

			bool statusChanged = this.companies.ChangeStatus(companyId);

			if (!statusChanged)
			{
				this.GenerateAlertMessage(string.Format(WebConstants.Message.BlockCompanyUnavailable, companyId), Alert.Danger);
				return RedirectToAction(nameof(All));
			}

			var companyName = this.companies.GetCompanyName(companyId);
			var companyStatus = this.companies.GetBlockStatus(companyId);

			this.GenerateAlertMessage(string.Format(WebConstants.Message.CompanyStatusChanged, companyName, companyStatus), Alert.Success);

			return RedirectToAction(nameof(All), new { page = page, filter = filter});
		}
    }
}

E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Areas/Admin/Views/AdminCompanies/All.cshtml
@model AllCompanies

@{
    ViewData["Title"] = "All Companies";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />

<form method="get" asp-controller="AdminCompanies" asp-action="All" class="form-inline row">
    <label asp-for="@Model.Filter"></label>
    <div class="form-group">
        <select asp-for="@Model.Filter" asp-items="Html.GetEnumSelectList<CompanyStatus>()" class="form-control"></select>
    </div>
    <input type="submit" value="Filter" class="btn btn-success" />
</form>
<br />

@if (Model.Companies.Count() == 0)
{
    @Html.Partial("_NoResultsFoundMessageBox")
}
else
{
    <hr />
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>URN</th>
                <th>Address</th>
                <th>Chief</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var company in Model.Companies)
            {
                <tr>
                    <td>@company.Name</td>
                    <td>@company.UniqueReferenceNumber</td>
                    <td>@company.Address</td>
                    <td>@company.Chief</td>
                    <td>@company.Email</td>
                    <td>@company.PhoneNumber</td>
                    <td>
                        @if (!company.IsApproved)
                        {
                            <a class="btn btn-primary" asp-action="Approve" asp-controller="AdminCompanies" asp-route-companyId="@company.Id" asp-route-filter="@Model.Filter" asp-route-page="@Model.Pagination.CurrentPage">Approve</a>
                        }

                        @if (!company.IsBlocked && company.IsApproved)
                        {
                            <a class="btn btn-danger" asp-action="Block" asp-controller="AdminCompanies" asp-route-companyId="@company.Id" asp-route-filter="@Model.Filter" asp-route-page="@Model.Pagination.CurrentPage">Block</a>
                        }
                        else if (company.IsBlocked)
                        {
                            <a class="btn btn-success" asp-action="Block" asp-controller="AdminCompanies" asp-route-companyId="@company.Id" asp-route-filter="@Model.Filter" asp-route-page="@Model.Pagination.CurrentPage">Unblock</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div class="container-fluid text-center">
        <ul class="pagination">
            <li class="page-item @(1 == Model.Pagination.CurrentPage ? "blocked":string.Empty)">
                <a class="page-link" asp-controller="@Model.Pagination.Controller" asp-action="@Model.Pagination.Action" asp-route-filter="@Model.Filter" asp-route-page="@Model.Pagination.PreviousPage">Previous</a>
            </li>
            @for (int i = 1; i <= Model.Pagination.TotalPages; i++)
            {
                <li class="page-item @(i == Model.Pagination.CurrentPage ? "active blocked":string.Empty)">
                    <a class="page-link" asp-controller="@Model.Pagination.Controller" asp-action="@Model.Pagination.Action" asp-route-filter="@Model.Filter" asp-route-page="@i">@i</a>
                </li>
            }
            <li class="page-item @(Model.Pagination.TotalPages == Model.Pagination.CurrentPage ? "blocked":string.Empty)">
                <a class="page-link" asp-controller="@Model.Pagination.Controller" asp-action="@Model.Pagination.Action" asp-route-filter="@Model.Filter" asp-route-page="@Model.Pagination.NextPage">Next</a>
            </li>
        </ul>
    </div>
}