E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Areas/Admin/Models/AdminUsers/AllUsers.cs
namespace ETicketSystem.Web.Areas.Admin.Models.AdminUsers
{
	using Services.Admin.Models;
	using System.Collections.Generic;
	using Web.Models.Pagination;

	public class AllUsers
    {
		public IEnumerable<AdminUserListingServiceModel> Users { get; set; }

		public PaginationViewModel Pagination { get; set; }
    }
}

E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Areas/Admin/Controllers/AdminUsersController.cs
namespace ETicketSystem.Web.Areas.Admin.Controllers
{
	using Common.Constants;
	using Common.Enums;
	using Data.Models;
	using Microsoft.AspNetCore.Identity;
	using Microsoft.AspNetCore.Mvc;
	using Models.AdminUsers;
	using Services.Admin.Contracts;
	using System.Threading.Tasks;
	using Web.Models.Pagination;

	public class AdminUsersController : BaseAdminController
    {
		public IAdminUserService users;

		private readonly UserManager<User> userManager;

		public AdminUsersController(IAdminUserService users, UserManager<User> userManager)
		{
			this.users = users;
			this.userManager = userManager;
		}

		[Route(WebConstants.Routing.AllUsers)]
		public async Task<IActionResult> All(string searchTerm, int page = 1)
		{
			if (page < 1)
			{
				return RedirectToAction(nameof(All), new { page = 1, searchTerm });
			}

			var users = await this.users.AllAsync(searchTerm, page, WebConstants.Pagination.AdminUsersListing);

			var usersPagination = new PaginationViewModel()
			{
				Action = nameof(All),
				Controller = WebConstants.Controller.AdminUsers,
				CurrentPage = page,
				PageSize = WebConstants.Pagination.AdminUsersListing,
				SearchTerm = searchTerm,
				TotalElements = this.users.TotalUsers(searchTerm)
			};

			if (page > usersPagination.TotalPages && usersPagination.TotalPages != 0)
			{
				return RedirectToAction(nameof(All), new { page = usersPagination.TotalPages, searchTerm });
			}

			return View(new AllUsers()
			{
				Users = users,
				Pagination = usersPagination
			});
		}

		[HttpPost]
		public async Task<IActionResult> ChangeRolesAsync(string userId, Role role, bool isRemove)
		{
			var user = await this.userManager.FindByIdAsync(userId);

			if (user == null)
			{
				this.GenerateAlertMessage(string.Format(WebConstants.Message.NonExistingEntity, nameof(WebConstants.Entity.User), userId), Alert.Danger);

				return RedirectToAction(nameof(All));
			}

			bool isInRole = await this.userManager.IsInRoleAsync(user, role.ToString());

			if (isRemove)
			{
				if (!isInRole)
				{
					this.GenerateAlertMessage(string.Format(WebConstants.Message.UserNotInRole, user.UserName, role.ToString()), Alert.Warning);

					return RedirectToAction(nameof(All));
				}

				await this.userManager.RemoveFromRoleAsync(user, role.ToString());

				this.GenerateAlertMessage(string.Format(WebConstants.Message.UserRemovedFromRole, user.UserName, role.ToString()), Alert.Success);
			}
			else
			{
				if (isInRole)
				{
					this.GenerateAlertMessage(string.Format(WebConstants.Message.UserAlreadyInRole, user.UserName, role.ToString()), Alert.Warning);

					return RedirectToAction(nameof(All));
				}

				await this.userManager.AddToRoleAsync(user, role.ToString());

				this.GenerateAlertMessage(string.Format(WebConstants.Message.UserAddedToRole, user.UserName, role.ToString()), Alert.Success);
			}

			return RedirectToAction(nameof(All));
		}
    }
}

E-Ticket-System-master/ETicketSystem.Web/ETicketSystem.Web/Areas/Admin/Views/AdminUsers/All.cshtml
@model AllUsers

@{
    ViewData["Title"] = "All Users";
}

<environment include="Development">
    <link rel="stylesheet" href="~/css/admin/admin-users.css" />
</environment>

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />
<div class="container-fluid">
    @Html.Partial("_SearchListingForm",Model.Pagination)
</div>
<hr />

@if (Model.Users.Count() == 0)
{
   @Html.Partial("_NoResultsFoundMessageBox")
}
else
{
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Username</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var u in Model.Users)
            {
                <tr>
                    <td>@u.Name</td>
                    <td>@u.Username</td>
                    <td>@u.Email</td>
                    <td class="user-roles">@(u.Roles.Count == 0 ? "No roles" : string.Join(", ", u.Roles))</td>
                    <td>
                        <form method="post">
                            <div class="form-group">                              
                                <select for="role" name="role" asp-items="@Html.GetEnumSelectList(typeof(Role)).Where(r => r.Text != Role.Company.ToString())" class="form-control"></select>
                            </div>
                            <button asp-controller="AdminUsers" asp-action="ChangeRolesAsync" asp-route-isRemove="false" asp-route-userId="@u.Id" type="submit" class="btn btn-primary @(u.Roles.Select(ur => ur.ToString()).SequenceEqual(Enum.GetNames (typeof(Role)).Where(r => r.ToString() != Role.Company.ToString())) ? "disabled" : string.Empty)">
                                Add to role
                            </button>
                            <button asp-controller="AdminUsers" asp-action="ChangeRolesAsync" asp-route-isRemove="true" asp-route-userId="@u.Id" type="submit" class="btn btn-danger  @(!u.Roles.Any() ? "disabled" : string.Empty)">
                                Remove from role
                            </button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    @Html.Partial("_Pagination", Model.Pagination)
}